# Selecting Rows and Columns

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/Large_Countries/large_countries_2015.csv",
                 index_col=0)

In [3]:
df.shape

(12, 3)

### Display Rows

Top 3

In [4]:
df.head(3)

              population  fertility      continent
Bangladesh  1.609956e+08       2.12           Asia
Brazil      2.078475e+08       1.78  South America
China       1.376049e+09       1.57           Asia

Bottom 3

In [5]:
df.tail(3)

                population  fertility      continent
Philippines    100699395.0       2.98           Asia
Russia         143456918.0       1.61         Europe
United States  321773631.0       1.97  North America

### Select columns

Select column by name

In [6]:
df['population']

Bangladesh       1.609956e+08
Brazil           2.078475e+08
China            1.376049e+09
India            1.311051e+09
Indonesia        2.575638e+08
Japan            1.265735e+08
Mexico           1.270172e+08
Nigeria          1.822020e+08
Pakistan         1.889249e+08
Philippines      1.006994e+08
Russia           1.434569e+08
United States    3.217736e+08
Name: population, dtype: float64

Select multiple columns by name.

In [12]:
df[['population','continent']]

                 population      continent
Bangladesh     1.609956e+08           Asia
Brazil         2.078475e+08  South America
China          1.376049e+09           Asia
India          1.311051e+09           Asia
Indonesia      2.575638e+08           Asia
Japan          1.265735e+08           Asia
Mexico         1.270172e+08  North America
Nigeria        1.822020e+08         Africa
Pakistan       1.889249e+08           Asia
Philippines    1.006994e+08           Asia
Russia         1.434569e+08         Europe
United States  3.217736e+08  North America

### Select Rows

1 row with .loc.

In [13]:
df.loc['Mexico']

population      127017224.0
fertility              2.13
continent     North America
Name: Mexico, dtype: object

multiple rows with .loc.

In [15]:
df.loc[['Mexico','Pakistan']]

           population  fertility      continent
Mexico    127017224.0       2.13  North America
Pakistan  188924874.0       3.04           Asia

In [17]:
df.head(1)

             population  fertility continent
Bangladesh  160995642.0       2.12      Asia

1 row with .iloc.

In [16]:
df.iloc[0]

population    160995642.0
fertility            2.12
continent            Asia
Name: Bangladesh, dtype: object

range of rows with .iloc.

In [18]:
df.iloc[3:7]

             population  fertility      continent
India      1.311051e+09       2.43           Asia
Indonesia  2.575638e+08       2.28           Asia
Japan      1.265735e+08       1.45           Asia
Mexico     1.270172e+08       2.13  North America

In [ ]:
df

Every second row

In [22]:
df[3::2]

                 population  fertility      continent
India          1.311051e+09       2.43           Asia
Japan          1.265735e+08       1.45           Asia
Nigeria        1.822020e+08       5.89         Africa
Philippines    1.006994e+08       2.98           Asia
United States  3.217736e+08       1.97  North America

### Take a column to the index and back

Let's set the continent to be the index.

In [25]:
cont = df.set_index('continent')
cont

                 population  fertility
continent
Asia           1.609956e+08       2.12
South America  2.078475e+08       1.78
Asia           1.376049e+09       1.57
Asia           1.311051e+09       2.43
Asia           2.575638e+08       2.28
Asia           1.265735e+08       1.45
North America  1.270172e+08       2.13
Africa         1.822020e+08       5.89
Asia           1.889249e+08       3.04
Asia           1.006994e+08       2.98
Europe         1.434569e+08       1.61
North America  3.217736e+08       1.97

Let's take it back to become a column.

In [26]:
resetted = cont.reset_index()
resetted

        continent    population  fertility
0            Asia  1.609956e+08       2.12
1   South America  2.078475e+08       1.78
2            Asia  1.376049e+09       1.57
3            Asia  1.311051e+09       2.43
4            Asia  2.575638e+08       2.28
5            Asia  1.265735e+08       1.45
6   North America  1.270172e+08       2.13
7          Africa  1.822020e+08       5.89
8            Asia  1.889249e+08       3.04
9            Asia  1.006994e+08       2.98
10         Europe  1.434569e+08       1.61
11  North America  3.217736e+08       1.97

In [27]:
df

                 population  fertility      continent
Bangladesh     1.609956e+08       2.12           Asia
Brazil         2.078475e+08       1.78  South America
China          1.376049e+09       1.57           Asia
India          1.311051e+09       2.43           Asia
Indonesia      2.575638e+08       2.28           Asia
Japan          1.265735e+08       1.45           Asia
Mexico         1.270172e+08       2.13  North America
Nigeria        1.822020e+08       5.89         Africa
Pakistan       1.889249e+08       3.04           Asia
Philippines    1.006994e+08       2.98           Asia
Russia         1.434569e+08       1.61         Europe
United States  3.217736e+08       1.97  North America

### Select both Rows and Columns

With loc

In [31]:
df.loc["China",["population","fertility"]]

population    1376048943.0
fertility             1.57
Name: China, dtype: object

With iloc (4 rows and 2 columns)

In [34]:
df.shape

(12, 3)

In [36]:
df.iloc[1:4, :3]

          population  fertility      continent
Brazil  2.078475e+08       1.78  South America
China   1.376049e+09       1.57           Asia
India   1.311051e+09       2.43           Asia

Broadcast English as the default value to a language column you just create.

In [38]:
df['language'] = 'English'
df

                 population  fertility      continent language
Bangladesh     1.609956e+08       2.12           Asia  English
Brazil         2.078475e+08       1.78  South America  English
China          1.376049e+09       1.57           Asia  English
India          1.311051e+09       2.43           Asia  English
Indonesia      2.575638e+08       2.28           Asia  English
Japan          1.265735e+08       1.45           Asia  English
Mexico         1.270172e+08       2.13  North America  English
Nigeria        1.822020e+08       5.89         Africa  English
Pakistan       1.889249e+08       3.04           Asia  English
Philippines    1.006994e+08       2.98           Asia  English
Russia         1.434569e+08       1.61         Europe  English
United States  3.217736e+08       1.97  North America  English

### Select by Conditions

Create a column "in_asia" that has the value true or false.

In [40]:
df['in_asia'] = df['continent']=='Asia'
df

                 population  fertility      continent language  in_asia
Bangladesh     1.609956e+08       2.12           Asia  English     True
Brazil         2.078475e+08       1.78  South America  English    False
China          1.376049e+09       1.57           Asia  English     True
India          1.311051e+09       2.43           Asia  English     True
Indonesia      2.575638e+08       2.28           Asia  English     True
Japan          1.265735e+08       1.45           Asia  English     True
Mexico         1.270172e+08       2.13  North America  English    False
Nigeria        1.822020e+08       5.89         Africa  English    False
Pakistan       1.889249e+08       3.04           Asia  English     True
Philippines    1.006994e+08       2.98           Asia  English     True
Russia         1.434569e+08       1.61         Europe  English    False
United States  3.217736e+08       1.97  North America  English    False

Select a subset of the df using North America as a filter.

In [41]:
df['continent']=='North America'

Bangladesh       False
Brazil           False
China            False
India            False
Indonesia        False
Japan            False
Mexico            True
Nigeria          False
Pakistan         False
Philippines      False
Russia           False
United States     True
Name: continent, dtype: bool

In [42]:
df[df['continent']=='North America']

                population  fertility      continent language  in_asia
Mexico         127017224.0       2.13  North America  English    False
United States  321773631.0       1.97  North America  English    False

Select a subset of the df including all countries with population between 100 - 250 million.

In [51]:
mid_pop = df[(df['population']>=1e6) &
            (df['population']<=250000000)]
mid_pop

              population  fertility      continent language  in_asia
Bangladesh   160995642.0       2.12           Asia  English     True
Brazil       207847528.0       1.78  South America  English    False
Japan        126573481.0       1.45           Asia  English     True
Mexico       127017224.0       2.13  North America  English    False
Nigeria      182201962.0       5.89         Africa  English    False
Pakistan     188924874.0       3.04           Asia  English     True
Philippines  100699395.0       2.98           Asia  English     True
Russia       143456918.0       1.61         Europe  English    False

Which countries in Asia have fertility rate smaller than 1.8?

In [49]:
low_fert_asia = df[(df['continent']=='Asia') &
                  (df['fertility']<1.8)]
low_fert_asia.index

Index(['China', 'Japan'], dtype='object')

In [60]:
df[(df['continent']=='Asia') &
                  (df['fertility']<1.8)].index

Index(['China', 'Japan'], dtype='object')

Same as above, but showing fertility and continent.

**df.loc[list_of_rows, list_of_columns]**

In [62]:
low_fert_asia = df.loc[(df['continent']=='Asia') & (df['fertility']<1.8), 
                       ['fertility', 'continent']]
                      
low_fert_asia.head(5)

       fertility continent
China       1.57      Asia
Japan       1.45      Asia

In [54]:
1e6, 10.0**6

# means 6 zeros at the end

(1000000.0, 1000000.0)