# Selecting Rows and Columns

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/Large_Countries/large_countries_2015.csv",
                 index_col=0)

In [3]:
df.shape

(12, 3)

### Display Rows

Top 3

In [5]:
...

Ellipsis

Bottom 3

In [6]:
...

Ellipsis

### Select columns

Select column by name

In [32]:
...

Bangladesh       1.609956e+08
Brazil           2.078475e+08
China            1.376049e+09
India            1.311051e+09
Indonesia        2.575638e+08
Japan            1.265735e+08
Mexico           1.270172e+08
Nigeria          1.822020e+08
Pakistan         1.889249e+08
Philippines      1.006994e+08
Russia           1.434569e+08
United States    3.217736e+08
Name: population, dtype: float64

Select multiple columns by name.

In [33]:
...

              population  fertility
Bangladesh  1.609956e+08       2.12
Brazil      2.078475e+08       1.78
China       1.376049e+09       1.57

### Select Rows

1 row with .loc.

In [34]:
...

population      2.07848e+08
fertility              1.78
continent     South America
Name: Brazil, dtype: object

multiple rows with .loc.

In [35]:
...

          population  fertility      continent
Japan   1.265735e+08       1.45           Asia
China   1.376049e+09       1.57           Asia
Brazil  2.078475e+08       1.78  South America

1 row with .iloc.

In [36]:
...

population      2.07848e+08
fertility              1.78
continent     South America
Name: Brazil, dtype: object

range of rows with .iloc.

In [6]:
...

             population  fertility continent
India      1.311051e+09       2.43      Asia
Indonesia  2.575638e+08       2.28      Asia
Japan      1.265735e+08       1.45      Asia

In [7]:
df

                 population  fertility      continent
Bangladesh     1.609956e+08       2.12           Asia
Brazil         2.078475e+08       1.78  South America
China          1.376049e+09       1.57           Asia
India          1.311051e+09       2.43           Asia
Indonesia      2.575638e+08       2.28           Asia
Japan          1.265735e+08       1.45           Asia
Mexico         1.270172e+08       2.13  North America
Nigeria        1.822020e+08       5.89         Africa
Pakistan       1.889249e+08       3.04           Asia
Philippines    1.006994e+08       2.98           Asia
Russia         1.434569e+08       1.61         Europe
United States  3.217736e+08       1.97  North America

Every second row

In [ ]:
df...

### Take a column to the index and back

Let's set the continent to be the index.

In [8]:
cont = ...

Let's take it back to become a column.

In [10]:
original = ...

### Select both Rows and Columns

With loc

In [43]:
df.loc[...]

            continent  fertility
Japan            Asia       1.45
China            Asia       1.57
Brazil  South America       1.78

With iloc (4 rows and 2 columns)

In [44]:
df.iloc[...]

             population  fertility
Brazil     2.078475e+08       1.78
China      1.376049e+09       1.57
India      1.311051e+09       2.43
Indonesia  2.575638e+08       2.28

Broadcast English as the default value to a language column you just create.

In [14]:
df
df

                 population  fertility      continent language
Bangladesh     1.609956e+08       2.12           Asia  English
Brazil         2.078475e+08       1.78  South America  English
China          1.376049e+09       1.57           Asia  English
India          1.311051e+09       2.43           Asia  English
Indonesia      2.575638e+08       2.28           Asia  English
Japan          1.265735e+08       1.45           Asia  English
Mexico         1.270172e+08       2.13  North America  English
Nigeria        1.822020e+08       5.89         Africa  English
Pakistan       1.889249e+08       3.04           Asia  English
Philippines    1.006994e+08       2.98           Asia  English
Russia         1.434569e+08       1.61         Europe  English
United States  3.217736e+08       1.97  North America  English

### Select by Conditions

Create a column "in_asia" that has the value true or false.

In [11]:
df['in_asia'] = ...
df

                 population  fertility      continent   in_asia
Bangladesh     1.609956e+08       2.12           Asia  Ellipsis
Brazil         2.078475e+08       1.78  South America  Ellipsis
China          1.376049e+09       1.57           Asia  Ellipsis
India          1.311051e+09       2.43           Asia  Ellipsis
Indonesia      2.575638e+08       2.28           Asia  Ellipsis
Japan          1.265735e+08       1.45           Asia  Ellipsis
Mexico         1.270172e+08       2.13  North America  Ellipsis
Nigeria        1.822020e+08       5.89         Africa  Ellipsis
Pakistan       1.889249e+08       3.04           Asia  Ellipsis
Philippines    1.006994e+08       2.98           Asia  Ellipsis
Russia         1.434569e+08       1.61         Europe  Ellipsis
United States  3.217736e+08       1.97  North America  Ellipsis

Select a subset of the df using North America as a filter.

In [12]:
...

Ellipsis

Select a subset of the df including all countries with population between 100 - 250 million.

In [50]:
mid_pop = df[df['population']....]
mid_pop

              population  fertility      continent language  in_asia
Bangladesh   160995642.0       2.12           Asia  English     True
Brazil       207847528.0       1.78  South America  English    False
Japan        126573481.0       1.45           Asia  English     True
Mexico       127017224.0       2.13  North America  English    False
Nigeria      182201962.0       5.89         Africa  English    False
Pakistan     188924874.0       3.04           Asia  English     True
Philippines  100699395.0       2.98           Asia  English     True
Russia       143456918.0       1.61         Europe  English    False

Which countries in Asia have fertility rate smaller than 1.8?

In [18]:
low_fert_asia = df[...]
low_fert_asia.index

Index(['China', 'Japan'], dtype='object')

Same as above, but showing fertility and continent.

In [19]:
low_fert_asia = df.loc[...]
low_fert_asia.head(5)

       fertility continent
China       1.57      Asia
Japan       1.45      Asia